### ISSUE TITLE
编译时出现错误

### ISSUE THREAD

**Issue by judy19980326** [KaleW515/fast-translate#1]
nihao，非常感谢你的分享，我在安装时出现一些问题，在check-dependency均已满足后，当我尝试make build时，出现：
rm -rf ./build
rm -rf ./disk
rm -rf ./test*
rm -rf ./tempCodeRunnerFile*
rm -rf ./cache
rm -rf *.spec
mkdir -p build/fast-translate/usr/bin
mkdir -p build/fast-translate/usr/share/applications
mkdir -p build/fast-translate/usr/share/icons
mkdir -p build/fast-translate/opt/fast-translate
cp pkg/aur/ftranslate build/fast-translate/usr/bin/
cp src/data/icon/logo.svg.png build/fast-translate/usr/share/icons/fast-translate.png
cp pkg/aur/fast-translate.desktop build/fast-translate/usr/share/applications/
cp -r src/* build/fast-translate/opt/fast-translate/
我应该如何处理，可以帮帮我吗，非常感谢

**Comment by KaleW515** [comment]
你好，可以提供一下完整的报错信息吗，目前复制的内容中没看到有报错的内容

**Comment by judy19980326** [comment]
好像就是没有报错，完整执行过程：
zhuyuedi@zhuyuedi:~/fast-translate$ make check-dependency
pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: httpx==0.23.0 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.23.0)
Requirement already satisfied: pynput==1.7.6 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.7.6)
Requirement already satisfied: PyQt5==5.15.6 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (5.15.6)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx==0.23.0->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: httpcore<0.16.0,>=0.15.0 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from httpx==0.23.0->-r requirements.txt (line 1)) (0.15.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from httpx==0.23.0->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: sniffio in /home/zhuyuedi/.local/lib/python3.10/site-packages (from httpx==0.23.0->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: python-xlib>=0.17 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from pynput==1.7.6->-r requirements.txt (line 2)) (0.31)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pynput==1.7.6->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: evdev>=1.3 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from pynput==1.7.6->-r requirements.txt (line 2)) (1.6.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from PyQt5==5.15.6->-r requirements.txt (line 3)) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from PyQt5==5.15.6->-r requirements.txt (line 3)) (12.11.0)
Requirement already satisfied: anyio==3.* in /home/zhuyuedi/.local/lib/python3.10/site-packages (from httpcore<0.16.0,>=0.15.0->httpx==0.23.0->-r requirements.txt (line 1)) (3.6.1)
Requirement already satisfied: h11<0.13,>=0.11 in /home/zhuyuedi/.local/lib/python3.10/site-packages (from httpcore<0.16.0,>=0.15.0->httpx==0.23.0->-r requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio==3.*->httpcore<0.16.0,>=0.15.0->httpx==0.23.0->-r requirements.txt (line 1)) (3.3)
zhuyuedi@zhuyuedi:~/fast-translate$ make build
rm -rf ./build
rm -rf ./disk
rm -rf ./test*
rm -rf ./tempCodeRunnerFile*
rm -rf ./cache
rm -rf *.spec
mkdir -p build/fast-translate/usr/bin
mkdir -p build/fast-translate/usr/share/applications
mkdir -p build/fast-translate/usr/share/icons
mkdir -p build/fast-translate/opt/fast-translate
cp pkg/aur/ftranslate build/fast-translate/usr/bin/
cp src/data/icon/logo.svg.png build/fast-translate/usr/share/icons/fast-translate.png
cp pkg/aur/fast-translate.desktop build/fast-translate/usr/share/applications/
cp -r src/* build/fast-translate/opt/fast-translate/
zhuyuedi@zhuyuedi:~/fast-translate$ make install
sudo rm -rf /opt/fast-translate
[sudo] zhuyuedi 的密码： 
sudo rm -rf /usr/bin/ftranslate /usr/share/icons/fast-translate.png /usr/share/applications/fast-translate.desktop
sudo mkdir -p /usr/bin/
sudo mkdir -p /usr/share/icons/
sudo cp -r ./build/fast-translate/opt/fast-translate /opt/
sudo cp build/fast-translate/usr/bin/* /usr/bin/
sudo cp build/fast-translate/usr/share/icons/* /usr/share/icons/
sudo cp build/fast-translate/usr/share/applications/* /usr/share/applications/
zhuyuedi@zhuyuedi:~/fast-translate$ 

@KaleW515

**Comment by KaleW515** [comment]
这看起来是没有报错的，我在ubuntu22 gnome虚拟机上试了一下，是可以正常用的，只是软件是基于qt开发的，在kde桌面上表现较好，在gnome上没有进行过细粒度的测试
