### ISSUE TITLE
无法打开图形化界面

### ISSUE THREAD

**Issue by Zeatar** [KaleW515/fast-translate#4]
感谢分享，但在执行完make和install之后无法打开GUI界面并配置相关参数，请问应该如何解决。

**Comment by KaleW515** [comment]
方便提供一下报错信息吗

**Comment by Zeatar** [comment]
现在是这样，我点击图标后不会打开相关的界面
![2023-04-25_10-51](https://user-images.githubusercontent.com/120762406/234163332-8c1698d1-0692-4a9a-ab53-895233f8fada.png)

**Comment by Zeatar** [comment]
这是build和install的执行情况
![2023-04-25_10-56](https://user-images.githubusercontent.com/120762406/234163533-a0acde45-4382-44ab-905e-27542264d5bc.png)

**Comment by KaleW515** [comment]
应该和是ubuntu的兼容性不太好，gnome是基于gtk的，这是基于qt的

**Comment by Zeatar** [comment]
好的，再次感谢分享
